version: "2"

services:
  # postgres:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   #volumes:
  #    # - ./postgres:/var/lib/postgresql/data
  #   #   - mysql-sock:/var/run/mysqld
  #   environment:
  #     POSTGRES_DB: dotnet
  #     POSTGRES_PASSWORD: dotnet
  #     POSTGRES_USER: dotnet
  #   restart: always
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "5m"
  #       max-file: "10"


  dotnet:
    image: movietime
    build: ./src
    ports:
      - 80:80
    restart: unless-stopped
    #environment:
      #DEV_UID: 1000
    #volumes:
    #  - ./config/appsettings.json:/app/appsettings.json
    #   - mysql-sock:/var/run/mysqld
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "10"